version: '3.8'

services:
  web:
    build: ./project
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=mysql+aiomysql://root:123@db:3306/foo
    depends_on:
      - db
  
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=foo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
