"""Add description and count to Song

Revision ID: 968b817525a2
Revises: 
Create Date: 2024-10-06 07:37:31.379681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '968b817525a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('description', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('song', sa.Column('count', sa.String(length=64), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'count')
    op.drop_column('song', 'description')
    # ### end Alembic commands ###